[2024-05-20T16:01:32.208+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_data_booking_test.save_data_to_postgresql scheduled__2024-05-19T02:00:00+00:00 [queued]>
[2024-05-20T16:01:32.223+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_data_booking_test.save_data_to_postgresql scheduled__2024-05-19T02:00:00+00:00 [queued]>
[2024-05-20T16:01:32.227+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2024-05-20T16:01:32.243+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_data_to_postgresql> on 2024-05-19 02:00:00+00:00
[2024-05-20T16:01:32.260+0000] {standard_task_runner.py:60} INFO - Started process 17668 to run task
[2024-05-20T16:01:32.271+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'api_data_booking_test', 'save_data_to_postgresql', 'scheduled__2024-05-19T02:00:00+00:00', '--job-id', '989', '--raw', '--subdir', 'DAGS_FOLDER/api_data_booking.py', '--cfg-path', '/tmp/tmpbkqo6ek5']
[2024-05-20T16:01:32.277+0000] {standard_task_runner.py:88} INFO - Job 989: Subtask save_data_to_postgresql
[2024-05-20T16:01:32.405+0000] {task_command.py:423} INFO - Running <TaskInstance: api_data_booking_test.save_data_to_postgresql scheduled__2024-05-19T02:00:00+00:00 [running]> on host e3e2dc6bc2be
[2024-05-20T16:01:32.674+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_data_booking_test' AIRFLOW_CTX_TASK_ID='save_data_to_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2024-05-19T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-19T02:00:00+00:00'
[2024-05-20T16:01:32.732+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-05-20T16:01:32.798+0000] {api_data_booking.py:168} ERROR - Error inserting booking data: duplicate key value violates unique constraint "booking_pkey"
DETAIL:  Key (booking_id)=(64156) already exists.

[2024-05-20T16:01:32.805+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-20T16:01:32.827+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=api_data_booking_test, task_id=save_data_to_postgresql, execution_date=20240519T020000, start_date=20240520T160132, end_date=20240520T160132
[2024-05-20T16:01:32.895+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-20T16:01:32.983+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
