[2024-05-17T05:40:40.320+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: temp_humi_dag.save_data_into_db manual__2024-05-17T05:40:29.558000+00:00 [queued]>
[2024-05-17T05:40:40.326+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: temp_humi_dag.save_data_into_db manual__2024-05-17T05:40:29.558000+00:00 [queued]>
[2024-05-17T05:40:40.327+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2024-05-17T05:40:40.334+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_data_into_db> on 2024-05-17 05:40:29.558000+00:00
[2024-05-17T05:40:40.338+0000] {standard_task_runner.py:60} INFO - Started process 4573 to run task
[2024-05-17T05:40:40.341+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'temp_humi_dag', 'save_data_into_db', 'manual__2024-05-17T05:40:29.558000+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/ICTTemp_Humi_DAG.py', '--cfg-path', '/tmp/tmpo9g9vez3']
[2024-05-17T05:40:40.343+0000] {standard_task_runner.py:88} INFO - Job 171: Subtask save_data_into_db
[2024-05-17T05:40:40.372+0000] {task_command.py:423} INFO - Running <TaskInstance: temp_humi_dag.save_data_into_db manual__2024-05-17T05:40:29.558000+00:00 [running]> on host e3e2dc6bc2be
[2024-05-17T05:40:40.417+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Group4' AIRFLOW_CTX_DAG_ID='temp_humi_dag' AIRFLOW_CTX_TASK_ID='save_data_into_db' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T05:40:29.558000+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T05:40:29.558000+00:00'
[2024-05-17T05:40:40.448+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-05-17T05:40:40.450+0000] {logging_mixin.py:188} INFO - Error: could not translate host name "172.20.10.2 host.docker.internal" to address: Name or service not known
[2024-05-17T05:40:40.451+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-17T05:40:40.457+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=temp_humi_dag, task_id=save_data_into_db, execution_date=20240517T054029, start_date=20240517T054040, end_date=20240517T054040
[2024-05-17T05:40:40.474+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-17T05:40:40.484+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
