[2024-05-20T12:19:43.127+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: temp_humi_dag.save_data_into_db manual__2024-05-20T12:14:31.867520+00:00 [queued]>
[2024-05-20T12:19:43.133+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: temp_humi_dag.save_data_into_db manual__2024-05-20T12:14:31.867520+00:00 [queued]>
[2024-05-20T12:19:43.135+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2024-05-20T12:19:43.143+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_data_into_db> on 2024-05-20 12:14:31.867520+00:00
[2024-05-20T12:19:43.148+0000] {standard_task_runner.py:60} INFO - Started process 944 to run task
[2024-05-20T12:19:43.151+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'temp_humi_dag', 'save_data_into_db', 'manual__2024-05-20T12:14:31.867520+00:00', '--job-id', '799', '--raw', '--subdir', 'DAGS_FOLDER/ICTTemp_Humi_DAG.py', '--cfg-path', '/tmp/tmpaahoxyy_']
[2024-05-20T12:19:43.154+0000] {standard_task_runner.py:88} INFO - Job 799: Subtask save_data_into_db
[2024-05-20T12:19:43.194+0000] {task_command.py:423} INFO - Running <TaskInstance: temp_humi_dag.save_data_into_db manual__2024-05-20T12:14:31.867520+00:00 [running]> on host e3e2dc6bc2be
[2024-05-20T12:19:43.243+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Group4' AIRFLOW_CTX_DAG_ID='temp_humi_dag' AIRFLOW_CTX_TASK_ID='save_data_into_db' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T12:14:31.867520+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-20T12:14:31.867520+00:00'
[2024-05-20T12:19:43.275+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-05-20T12:19:43.290+0000] {sql.py:450} INFO - Running statement: 
                INSERT INTO temp_and_humi (date, time, temperature, humidity, heat)
                VALUES (%s, %s, %s, %s, %s);
                , parameters: ('2024-01-01', '00:00:00', 22.91, 75.68, 73.24)
[2024-05-20T12:19:43.297+0000] {logging_mixin.py:188} INFO - Error: duplicate key value violates unique constraint "temp_and_humi_pkey"
DETAIL:  Key (date, "time")=(2024-01-01, 00:00:00) already exists.
[2024-05-20T12:19:43.300+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-20T12:19:43.309+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=temp_humi_dag, task_id=save_data_into_db, execution_date=20240520T121431, start_date=20240520T121943, end_date=20240520T121943
[2024-05-20T12:19:43.324+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-20T12:19:43.334+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
