[2024-05-17T04:08:43.400+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: temp_humi_dag.save_data_into_db scheduled__2024-05-16T00:00:00+00:00 [queued]>
[2024-05-17T04:08:43.406+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: temp_humi_dag.save_data_into_db scheduled__2024-05-16T00:00:00+00:00 [queued]>
[2024-05-17T04:08:43.407+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2024-05-17T04:08:43.415+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_data_into_db> on 2024-05-16 00:00:00+00:00
[2024-05-17T04:08:43.420+0000] {standard_task_runner.py:60} INFO - Started process 868 to run task
[2024-05-17T04:08:43.423+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'temp_humi_dag', 'save_data_into_db', 'scheduled__2024-05-16T00:00:00+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/ICTTemp_Humi_DAG.py', '--cfg-path', '/tmp/tmpru_7bv86']
[2024-05-17T04:08:43.425+0000] {standard_task_runner.py:88} INFO - Job 126: Subtask save_data_into_db
[2024-05-17T04:08:43.459+0000] {task_command.py:423} INFO - Running <TaskInstance: temp_humi_dag.save_data_into_db scheduled__2024-05-16T00:00:00+00:00 [running]> on host e3e2dc6bc2be
[2024-05-17T04:08:43.506+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Group4' AIRFLOW_CTX_DAG_ID='temp_humi_dag' AIRFLOW_CTX_TASK_ID='save_data_into_db' AIRFLOW_CTX_EXECUTION_DATE='2024-05-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-16T00:00:00+00:00'
[2024-05-17T04:08:43.537+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-05-17T04:08:43.550+0000] {sql.py:450} INFO - Running statement: 
                INSERT INTO temp_and_humi (date, time, temperature, humidity, heat)
                VALUES (%s, %s, %s, %s, %s);
                , parameters: ('2024-01-01', '00:00:00', 26.18, 23.61, 79.12)
[2024-05-17T04:08:43.557+0000] {logging_mixin.py:188} INFO - Error: duplicate key value violates unique constraint "temp_and_humi_pkey"
DETAIL:  Key (date, "time")=(2024-01-01, 00:00:00) already exists.
[2024-05-17T04:08:43.558+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-17T04:08:43.566+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=temp_humi_dag, task_id=save_data_into_db, execution_date=20240516T000000, start_date=20240517T040843, end_date=20240517T040843
[2024-05-17T04:08:43.596+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-17T04:08:43.611+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
